/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poo.trabalho_final.view;

import com.poo.trabalho_final.controller.FileHandler;
import com.poo.trabalho_final.model.Excursao;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pedro Lucas
 */
public class ExcursaoVerTodas extends javax.swing.JFrame {

    /**
     * Creates new form ExcursaoVerTodas
     */
    public ExcursaoVerTodas() {
        initComponents();
        this.listAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbExcursoesTabela = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 300));

        lbExcursoesTabela.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbExcursoesTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbExcursoesTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcursaoVerTodas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcursaoVerTodas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcursaoVerTodas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcursaoVerTodas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcursaoVerTodas().setVisible(true);
            }
        });
    }

    public final void listAll() {
        String html = "";
        html += ("<html>");
        html += ("<head>");
        html += ("<style>");
        html += ("table, th, td { border:1px solid black; }");
        html += ("</style>");
        html += ("</head>");
        html += ("<body>");
        html += ("<table style=\"width:350px\">");
        html += ("<tr>");
        html += ("<th>Partida</th>");
        html += ("<th>Destino</th>");
        html += ("<th>Submarino</th>");
        html += ("</tr>");
        File root = new File("./data/excursoes");
        for (final File file : root.listFiles()) {
            try {
                FileHandler<Excursao> fileHandler = new FileHandler();
                Excursao e = fileHandler.read(file.getAbsolutePath());
                html += ("<tr>");
                html += ("<td>" + e.getPartida() + "</td>");
                html += ("<td>" + e.getDestino().getNome() + "</td>");
                html += ("<td>" + e.getSubmarino().getNome() + "</td>");
                html += ("</tr>");
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(ExcursaoVerTodas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        html += ("</table>");
        html += ("</body>");
        html += ("</html>");

        lbExcursoesTabela.setText(html);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbExcursoesTabela;
    // End of variables declaration//GEN-END:variables
}
